import Link from "next/link";
import { ArrowLeft, MessageSquareText, Search, Subtitles, Video } from "lucide-react";
import { PhaseNotice } from "@/components/foundation/phase-notice";
import { AppShell } from "@/components/layout/app-shell";

export default async function VideoWorkspacePage({ params }: PageProps<"/video/[id]">) {
  const { id } = await params;
  return <AppShell compact><div className="mb-6"><Link href="/library" className="inline-flex items-center gap-2 text-sm text-zinc-600 hover:text-zinc-950 dark:text-zinc-400 dark:hover:text-white"><ArrowLeft className="size-4" />Biblioteca</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wider text-zinc-500">Espaço de trabalho</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Vídeo em preparação</h1><p className="mt-1 text-sm text-zinc-500">Projeto {id}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-medium text-amber-800 dark:bg-amber-950/50 dark:text-amber-300">Aguardando importação</span></div></div><div className="grid gap-6 lg:grid-cols-[minmax(0,1.85fr)_minmax(20rem,1fr)]"><section className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="grid aspect-video place-items-center bg-zinc-950 text-center text-zinc-400"><div><Video className="mx-auto size-8 text-zinc-600" /><p className="mt-3 text-sm">O player será exibido após a importação.</p></div></div><div className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Transcrição</h2><Search className="size-4 text-zinc-400" /></div><div className="mt-4 rounded-xl border border-dashed border-zinc-300 p-5 text-sm leading-6 text-zinc-500 dark:border-zinc-700">Os segmentos com timestamps e a busca serão habilitados nas próximas fases.</div></div></section><aside className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-center gap-2"><MessageSquareText className="size-4 text-violet-600 dark:text-violet-400" /><h2 className="font-semibold">Assistente de IA</h2></div><div className="mt-5 flex min-h-72 flex-col items-center justify-center text-center"><span className="grid size-10 place-items-center rounded-xl bg-zinc-100 text-zinc-500 dark:bg-zinc-800"><Subtitles className="size-5" /></span><p className="mt-4 text-sm font-medium">Pergunte qualquer coisa sobre este vídeo.</p><p className="mt-2 text-sm leading-6 text-zinc-500">O chat será liberado assim que houver uma transcrição e um provedor configurado.</p></div><div className="rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-3 text-sm text-zinc-400 dark:border-zinc-800 dark:bg-zinc-950">Faça uma pergunta sobre o vídeo...</div></aside></div><div className="mt-6"><PhaseNotice>Este é o espaço de trabalho da Fase 5. Player, transcrição, busca e chat ainda não processam dados reais.</PhaseNotice></div></AppShell>;
}
